name: 'Set default values'
description: 'Set default values for FoD environment variables like FOD_RELEASE'
author: 'Fortify'
runs:
  using: composite
  steps:
    - name: Set default FoD release name
      if: ${{ !env.FOD_RELEASE }}
      run: |
        export FOD_RELEASE="${APP}:${REL}"
        echo FOD_RELEASE=$FOD_RELEASE >> $GITHUB_ENV
        echo "Configured default value for FOD_RELEASE: ${FOD_RELEASE}"
      shell: bash
      env:
        APP: ${{ github.repository }}
        REL: ${{ github.head_ref || github.ref_name }}
    - name: Configure --oss setup / -oss package options if Debricked scan enabled
      if: ${{ env.DO_DEBRICKED_SCAN=='true' }}
      run: |
        # Configure --oss setup / -oss package options if Debricked scan enabled. Note that
        # composite actions can't override user-provided environment variables, so we use
        # a GitHub Action specific environment variable that will be automatically expanded
        # in internal/run-script/scripts/common.sh.
        #
        # Platform-independent regexes looking for -oss/--oss options with word boundaries
        # See 'Optional reading' section at https://stackoverflow.com/a/12696899
        PKG_REGEX="(^|[^[:alnum:]_])-oss([^[:alnum:]_]|$)"
        SETUP_REGEX="(^|[^[:alnum:]_])--oss([^[:alnum:]_]|$)"
        if [[ ! $EXTRA_PACKAGE_OPTS =~ $PKG_REGEX && ! $PACKAGE_EXTRA_OPTS =~ $PKG_REGEX ]]; then
          echo "GHA_PACKAGE_EXTRA_OPTS=-oss" >> $GITHUB_ENV
        fi 
        if [[ ! $SETUP_EXTRA_OPTS =~ $SETUP_REGEX ]]; then
          echo "GHA_SETUP_EXTRA_OPTS=--oss" >> $GITHUB_ENV
        fi 
      shell: bash
    - name: Configure --app-owner option if authentication with user credentials
      if: ${{ env.FOD_USER && env.DO_SETUP=='true' }}
      run: |
        # Configure --app-owner option if setup is enabled and FoD user is available. Note 
        # that composite actions can't override user-provided environment variables, so we use
        # a GitHub Action specific environment variable that will be automatically expanded
        # in internal/run-script/scripts/common.sh.
        #
        # Platform-independent regex looking for --app-owner option with word boundaries
        # See 'Optional reading' section at https://stackoverflow.com/a/12696899
        SETUP_REGEX="(^|[^[:alnum:]_])--app-owner"
        if [[ ! $SETUP_EXTRA_OPTS =~ $SETUP_REGEX ]]; then
          echo "GHA_SETUP_EXTRA_OPTS=--app-owner "${FOD_USER}" ${GHA_SETUP_EXTRA_OPTS}" >> $GITHUB_ENV
        fi 
      shell: bash
                
branding:
  icon: 'shield'
  color: 'blue'

