name: 'Export SSC vulnerability data to GitHub'
description: 'Export SSC vulnerability data to GitHub'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: fortify/github-action/internal/set-ssc-var-defaults@feat-1.3.0
    - uses: fortify/github-action/setup@feat-1.3.0
      with:
        export-path: false
        fcli: action-default
    - uses: fortify/github-action/internal/ssc-login@feat-1.3.0
    - run: ${FCLI_CMD} ssc action run github-sast-report --av "${SSC_APPVERSION}" -f ./gh-fortify-sast.sarif
      shell: bash
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./gh-fortify-sast.sarif

    # Optionally store the generated file for troubleshooting purposes.
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: sarif-files
        path: ./gh-fortify-sast.sarif

branding:
  icon: 'shield'
  color: 'blue'

