name: 'Perform SAST scan'
description: 'Perform a SAST scan on ScanCentral SAST'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: fortify/github-action/internal/set-ssc-var-defaults@feat-1.3.0
    - uses: fortify/github-action/setup@feat-1.3.0
      with:
        export-path: false
        fcli: action-default
        debricked-cli: ${{ env.DO_DEBRICKED_SCAN=='true' && 'action-default' || 'skip' }}
    - uses: fortify/github-action/internal/ssc-login@feat-1.3.0
    - uses: fortify/github-action/internal/sc-sast-login@feat-1.3.0
    - uses: fortify/github-action/package@feat-1.3.0
    - uses: fortify/github-action/internal/run-script@feat-1.3.0
      with:
        script: sc-sast-and-debricked-scan.sh
      env: 
        DO_SC_SAST_SCAN: true
        GITHUB_TOKEN: ${{ github.token }}
    - if: env.DO_EXPORT == 'true'
      uses: fortify/github-action/ssc-export@feat-1.3.0
        
branding:
  icon: 'shield'
  color: 'blue'

