name: 'Set up Java for ScanCentral Client'
description: 'Set SCANCENTRAL_JAVA_HOME with Java version as required by ScanCentral Client, while retaining original Java version (if available) as default. Note that this action does not set up ScanCentral Client itself.'
author: 'Fortify'
runs:
  using: composite
  steps:
    - name: Store original JAVA_HOME
      run: |
        echo "ORG_JAVA_HOME=${{ env.JAVA_HOME }}" >> ${GITHUB_ENV}
      shell: bash
    - name: Setup required Java version for ScanCentral Client
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21' # ScanCentral Client 24.2+ requires Java17+
        overwrite-settings: false
    - name: Set SCANCENTRAL_JAVA_HOME
      run: |
        echo "SCANCENTRAL_JAVA_HOME=${{ env.JAVA_HOME }}" >> ${GITHUB_ENV}
      shell: bash
    - name: Restore original JAVA_HOME and update PATH
      if: ${{ env.ORG_JAVA_HOME }}
      run: |
        echo "JAVA_HOME=${{ env.ORG_JAVA_HOME }}" >> ${GITHUB_ENV}
        echo "${{ env.ORG_JAVA_HOME }}/bin" >> ${GITHUB_PATH}
      shell: bash
                
branding:
  icon: 'shield'
  color: 'blue'

