name: 'Package source code & dependencies'
description: 'Package source code & dependencies for SAST & SCA scans'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: fortify/github-action/internal/setup-java-for-sc-client@v1.3.1
    - uses: fortify/github-action/setup@v1.3.1
      with:
        export-path: false
        sc-client: action-default
    - uses: fortify/github-action/internal/run-script@v1.3.1
      with:
        script: package.sh
        
branding:
  icon: 'shield'
  color: 'blue'

